print-status: False
api:
    name: IdealizarWhatsAppManagerApi
    extension: yml
    dependency:
        update: False
        list:
            web: [Popen,Path]
            local: []
    list: [globals]
    language: EN-US
    git:
        url: https://github.com/SamuelJansen/
        extension: git

    security:
        secret: default
    server:
        scheme: https
        host: 0.0.0.0
        port: 5500
        base-url: /idealizar-whats-app-manager-api
        complete-url: ${api.server.scheme}://${swagger.host}:${api.server.port}${api.server.base-url}
    # database:
        # dialect: ${DATABASE_DIALECT:}
        # driver: ${DATABASE_DRIVER:}
        # database: ${DATABASE_NAME:}
        # username: ${DATABASE_USERNAME:}
        # password: ${DATABASE_PASSWORD:}
        # host: ${DATABASE_HOST:}
        # port: ${DATABASE_PORT:}
        # schema: ${DATABASE_SCHEMA:}
idealizar:
    whats-app:
        web:
            base-url: http://192.168.25.2:5100/idealizar-whats-app-web-api
            request-timeout: 22
    agenda:
        base-url: http://192.168.25.2:5110/idealizar-agenda-api
        request-timeout: 3

wit-ai:
  app-version: 20210601
  authorization: ${WIT_AI_AUTHORIZATION:}
  base-url: https://api.wit.ai

swagger:
    host: ${api.server.host}:${api.server.port}
    schemes: [${api.server.scheme}]
    info:
        title: {api.name}
        version: 0.0.1
        description: Riachuelo automating api
        terms-of-service: http://swagger.io/terms/
        contact:
            name: Samuel Jansen
            email: samuel.jansenn@gmail.com
        license:
            name: Apache 2.0 / MIT License
            url: http://www.apache.org/licenses/LICENSE-2.0.html

python:
    version: 3.9
